db:
  image: mysql:latest
  container_name: db-api
  volumes:
   - /var/lib/mysql
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=lumen
   - MYSQL_USER=user
   - MYSQL_PASSWORD=password

phpfpm:
  image: lyberteam/php-fpm-7.1
  container_name: phpfpm-api
  links:
    - db:db
  ports:
   - "9000:9000"
  volumes:
   - ./html:/srv/http

server:
  image: nginx:latest
  container_name: server-api
  links:
    - phpfpm:phpfpm
  ports:
   - "8000:80"
   - "443:443"
  volumes:
   - ./html:/usr/share/nginx/html
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf